# SAM configuration file for Smalruby infrastructure

version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "smalruby-infrastructure"
region = "ap-northeast-1"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "smalruby-infrastructure"
parameter_overrides = "Stage=prod"

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"